# Generated by Django 3.2.2 on 2021-05-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
